name: Build Agenda for meetings
on:
  issues:
    types: [labeled, unlabeled]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: wesleytodd/meeting-maker@v0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        schedules: 2020-04-22T16:00:00.0Z/P2W # first occurance of the meeting and recurrance schedule
        createWithin: P2D # create agenda within 2 days of the meeting
        issueTitle: "WG Meeting <%= date.toFormat('yyyy-MM-dd') %>"
        labels: meeting
        agendaLabel: meeting-agenda
