name: GPU_TEST
on:
  push:
    branches:
      - 'main'
  pull_request:
jobs:
  ubuntu-gpu:
    runs-on: ubuntu-20.04-gpu-t4-4c-16g-176h
    steps:
      - name: Update APT repo for CUDA
        run: |
            cat /etc/os-release
            nvidia-smi
