name: Send meeting agenda to email list
on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: timheuer/issue-notifier@v1
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      with:
        fromMailAddress: 'tac@lists.aswf.io'
        toMailAddress: '[MAILING LIST EMAIL]'
        subject: '[COMMUNITY NAME] Working Group meeting agenda for today'
        labelsToMonitor: 'meeting'
